Repository SMUING-D/FE-React2, pull requests merged in 2024-02, with the labels that each got.

#31 Feat#22
  smuing/src/App.tsx
  smuing/src/components/countupcard/CountUpCard.tsx
  smuing/src/components/herobox/HeroBox.tsx
  smuing/src/components/infiniteslider/InfiniteSlider.tsx
  smuing/src/components/infiniteslidercard/InfiniteSliderCard.tsx
  smuing/src/components/introducebox/IntoroduceBox.tsx
  smuing/src/components/navbar/Navbar.tsx
  smuing/src/components/newsbox/NewsBox.tsx
  smuing/src/components/partintro/PartIntro.tsx
  smuing/src/components/projectcard/ProjectCard.tsx
  smuing/src/index.css
  smuing/src/main.tsx
  smuing/src/pages/AddProject.tsx
  smuing/src/pages/FormPage.tsx
  smuing/src/pages/LoginPage.tsx
  smuing/src/pages/MainPage.tsx
  smuing/src/redux/actions/sidebarActions.ts
  smuing/src/redux/slices/sidebarSlice.ts
  smuing/src/redux/store/store.ts
Labels: design

#35 프로젝트 등록, 공지사항 등록, 로그인 input
  smuing/src/App.tsx
  smuing/src/constants/ADD_ANNOUNCE.ts
  smuing/src/constants/ADD_PROJECT.ts
  smuing/src/pages/AddAnnounce.tsx
  smuing/src/pages/AddProject.tsx
  smuing/src/types/types.ts
Labels: feat

#32 Feat#30
  smuing/src/App.tsx
  smuing/src/components/countupcard/CountUpCard.tsx
  smuing/src/components/footer/Footer.tsx
  smuing/src/components/formcontents/FormContents.tsx
  smuing/src/components/formoption/FormOption.tsx
  smuing/src/components/formtitlebox/FormTitleBox.tsx
  smuing/src/components/herobox/HeroBox.tsx
  smuing/src/components/introducebox/IntoroduceBox.tsx
  smuing/src/components/navbar/Navbar.tsx
  smuing/src/components/newsbox/NewsBox.tsx
  smuing/src/components/partintro/PartIntro.tsx
  smuing/src/components/projectcard/ProjectCard.tsx
  smuing/src/components/projectslist/ProjectList.tsx
  smuing/src/components/sidebar/Sidebar.tsx
  smuing/src/constants/COUNTUP_DATA.ts
  smuing/src/constants/FOOTER_ICONS.tsx
  smuing/src/constants/HERO_TEST_ARR.ts
  smuing/src/constants/NEWS_DATA.ts
  smuing/src/constants/PART_INTRO_DATA.ts
  smuing/src/constants/PROJECTS_DATA.ts
  smuing/src/hooks/useFormHandling.ts
  smuing/src/pages/FormPage.tsx
  smuing/src/pages/MainPage.tsx
  smuing/src/types/types.ts
Labels: feat

#38 feat#36: 무한 슬라이더 구현
  smuing/package-lock.json
  smuing/package.json
  smuing/src/App.tsx
  smuing/src/components/formtitlebox/FormTitleBox.tsx
  smuing/src/components/infiniteslider/InfiniteSlider.tsx
  smuing/src/components/infiniteslidercard/InfiniteSliderCard.tsx
  smuing/src/pages/MainPage.tsx
  smuing/src/types/types.ts
  smuing/yarn.lock
Labels: enhancement

#41 Feat#37 공지사항 상세
  smuing/src/App.tsx
  smuing/src/components/announce/TextBox.tsx
  smuing/src/components/announce/TruncatedText.tsx
  smuing/src/constants/ANNOUNCE_DATA.ts
  smuing/src/constants/DETAIL_ANNOUNCE.ts
  smuing/src/pages/AllAnnounce.tsx
  smuing/src/pages/DetailAnnounce.tsx
  smuing/src/types/types.ts
Labels: feat

#33 Feat#29 프로젝트 등록, 공지사항 등록, 로그인 input 구현 - 비활성화 머지 안할것
  .DS_Store
  .gitignore
  smuing/.gitignore
  smuing/src/components/login/Join.tsx
  smuing/src/components/login/LoginBox.tsx
  smuing/src/constants/JOIN.ts
  smuing/src/types/types.ts
Labels: feat

#49 feat#48: cors 테스트
  smuing/src/components/login/Join.tsx
  smuing/src/components/pagination/Pagination.tsx
  smuing/src/pages/MainPage.tsx
Labels: enhancement
